# Generated by Django 4.2.4 on 2023-10-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_payments_order_remove_payments_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('GPay', 'GPay'), ('Paypal', 'Paypal'), ('Paytm', 'Paytm')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orders')),
            ],
        ),
    ]
