name: django-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with: 
          host: ""
          port: 22 # optional, default is 22
          user: ""
          pass: "" # Use a secret for sensitive information (recommended)
          connect_timeout: 30 # optional, default is 30s
          script: |
            # Your deployment script or commands go here
            # For example:
            echo "Hello, deploying your Django application!"
            cd /path/to/your/django/project
            git pull origin main
            source /path/to/your/virtualenv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl restart gunicorn  # or any other command to restart your Django server

